repos:
- repo: local
  hooks:
    - id: sanitize-python-notebooks
      name: Sanitize python notebooks to commit properly
      language: python
      entry: 'jupyter nbconvert --to notebook --inplace --ClearOutputPreprocessor.enabled=True --ClearMetadataPreprocessor.enabled=True --execute'
      files: '.ipynb$'
      stages: ['pre-commit']
      fail_fast: false